runtime: python311
entrypoint: gunicorn -b :$PORT app:app

instance_class: F1

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 3s
  max_pending_latency: 15s
  max_concurrent_requests: 80

env_variables:
  FLASK_ENV: "production"
  FLASK_DEBUG: "0"
  ATTENDANCE_SPREADSHEET_ID: "1i8QqDWXnPd3zfNyUTJ9hV1NipnByxy53sz4_jKkHOs8"
  GOOGLE_SHEETS_CREDENTIALS: "service_key.json"

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto